package com.soapclient.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2025-07-13T01:32:15.435Z
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://localhost/sunu_site/sunu_site_web/soap_server.php", name = "UserServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UserServicePortType {

    @WebMethod(action = "http://localhost/sunu_site/sunu_site_web/soap_server.php#updateUser")
    @WebResult(name = "updateUserResponse", targetNamespace = "http://localhost/sunu_site/sunu_site_web/soap_server.php", partName = "parameters")
    public UpdateUserResponse updateUser(

        @WebParam(partName = "parameters", name = "updateUserRequest", targetNamespace = "http://localhost/sunu_site/sunu_site_web/soap_server.php")
        UpdateUserRequest parameters
    );

    @WebMethod(action = "http://localhost/sunu_site/sunu_site_web/soap_server.php#deleteUser")
    @WebResult(name = "deleteUserResponse", targetNamespace = "http://localhost/sunu_site/sunu_site_web/soap_server.php", partName = "parameters")
    public DeleteUserResponse deleteUser(

        @WebParam(partName = "parameters", name = "deleteUserRequest", targetNamespace = "http://localhost/sunu_site/sunu_site_web/soap_server.php")
        DeleteUserRequest parameters
    );

    @WebMethod(action = "http://localhost/sunu_site/sunu_site_web/soap_server.php#authenticateUser")
    @WebResult(name = "authenticateUserResponse", targetNamespace = "http://localhost/sunu_site/sunu_site_web/soap_server.php", partName = "parameters")
    public AuthenticateUserResponse authenticateUser(

        @WebParam(partName = "parameters", name = "authenticateUserRequest", targetNamespace = "http://localhost/sunu_site/sunu_site_web/soap_server.php")
        AuthenticateUserRequest parameters
    );

    @WebMethod(action = "http://localhost/sunu_site/sunu_site_web/soap_server.php#listUsers")
    @WebResult(name = "listUsersResponse", targetNamespace = "http://localhost/sunu_site/sunu_site_web/soap_server.php", partName = "parameters")
    public ListUsersResponse listUsers(

        @WebParam(partName = "parameters", name = "listUsersRequest", targetNamespace = "http://localhost/sunu_site/sunu_site_web/soap_server.php")
        ListUsersRequest parameters
    );

    @WebMethod(action = "http://localhost/sunu_site/sunu_site_web/soap_server.php#addUser")
    @WebResult(name = "addUserResponse", targetNamespace = "http://localhost/sunu_site/sunu_site_web/soap_server.php", partName = "parameters")
    public AddUserResponse addUser(

        @WebParam(partName = "parameters", name = "addUserRequest", targetNamespace = "http://localhost/sunu_site/sunu_site_web/soap_server.php")
        AddUserRequest parameters
    );
}
